# base image
FROM node:10.12.0

RUN wget -qO- https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get update && apt-get install -yq nodejs

ARG DIR="/frontend"
# set working directory
RUN mkdir ${DIR}
WORKDIR ${DIR}

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH ${DIR}/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json ${DIR}/package.json
RUN npm install
RUN npm install -g @angular/cli
RUN npm rebuild node-sass --force

# add app
COPY . ${DIR}
